name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - name: Type Check
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test
